image: quay.io/biocat/bdcat-integration-tests:0.2

stages:
  - test

variables:
    GOOGLE_PROJECT_NAME: firecloud-cgl
    WORKSPACE_NAME: terra-notebook-utils-tests
    GOOGLE_PROJECT_ID: drs-billing-project

before_script:
  - date && date -u
  - source environment
  - make lint
  - echo -n ${ENCODED_GOOGLE_APPLICATION_CREDENTIALS} | base64 -d > ${CI_PROJECT_DIR}/gcp-creds.json
  # Don't set GOOGLE_APPLICATION_CREDENTIALS to so that some tests are still
  # unauthenticated. Use directly when needed.

after_script:
  - /venv/bin/python scripts/post_to_slack.py

.staging_job: &staging_job
  stage: test
  variables:
    BDCAT_STAGE: staging
    TERRA_DEPLOYMENT_ENV: alpha
  except:
    - schedules
    - prod

staging__basic_submission:
  <<: *staging_job
  script:
    - /venv/bin/python test/test_basic_submission.py

staging__version_check:
  <<: *staging_job
  script:
    - /venv/bin/python test/test_version_check.py

prod__basic_submission:
  stage: test
  variables:
    BDCAT_STAGE: prod
  script:
    - /venv/bin/python test/test_basic_submission.py
  except:
    - master
    - staging
