image: images.sbgenomics.com/seven-bridges-qa/bdcat-integration-tests

stages:
  - test

before_script:
  - date && date -u

after_script:
  - /venv/bin/python scripts/post_to_slack.py

.prepare_staging_env: &prepare_staging_env
  before_script:
    - export GOOGLE_PROJECT_NAME=firecloud-cgl
    - export WORKSPACE_NAME=terra-notebook-utils-tests
    - export GOOGLE_PROJECT_ID=drs-billing-project
    - export BDCAT_STAGE=staging
    - export TERRA_DEPLOYMENT_ENV=alpha

staging:
  stage: test
  <<: *prepare_staging_env
  script:
    - source environment
    - make lint
    - /venv/bin/python test/test_basic_submission.py
  except:
    - schedules
    - prod

version_check:
  stage: test
  <<: *prepare_staging_env
  script:
    - source environment
    - make lint
    - /venv/bin/python test/test_version_check.py
  except:
    - schedules
    - prod

prod:
  stage: test
  script:
    - source environment
    - make lint
    - export BDCAT_STAGE=prod
    - /venv/bin/python test/test_basic_submission.py
  except:
    - master
    - staging
