image: images.sbgenomics.com/seven-bridges-qa/bdcat-integration-tests:2021-10-22

stages:
  - test

variables:
    GOOGLE_PROJECT_NAME: firecloud-cgl
    WORKSPACE_NAME: terra-notebook-utils-tests
    GOOGLE_PROJECT_ID: drs-billing-project
    TERRA_DEPLOYMENT_ENV: alpha

before_script:
  - date && date -u
  - source environment
  - make lint

after_script:
  - /venv/bin/python scripts/post_to_slack.py

.staging_job: &staging_job
  stage: test
  variables:
    BDCAT_STAGE: staging
  except:
    - schedules
    - prod

staging__basic_submission:
  <<: *staging_job
  script:
    - /venv/bin/python test/test_basic_submission.py

staging__version_check:
  <<: *staging_job
  script:
    - /venv/bin/python test/test_version_check.py

prod__basic_submission:
  stage: test
  variables:
    BDCAT_STAGE: prod
  script:
    - /venv/bin/python test/test_basic_submission.py
  except:
    - master
    - staging
