image: ubuntu:18.04
# TODO: build image

stages:
  - test

before_script:
  - date && date -u
  - apt-get update && apt-get install -y python3.8 python3.8-dev python3-pip python-pip virtualenv git

unit_tests:
  stage: test
  script:
    - source environment
    - virtualenv -p python3.8 venv && . venv/bin/activate
    - git clone https://github.com/DataBiosphere/terra-notebook-utils.git  && cd terra-notebook-utils && python setup.py install
    - cd .. && pip install -r requirements.txt
    - test/test_basic_submission.py

scheduled_tests:
  only:
    - schedules
  script:
    - source environment
    - virtualenv -p python3.8 venv && . venv/bin/activate
    - git clone https://github.com/DataBiosphere/terra-notebook-utils.git  && cd terra-notebook-utils && python setup.py install
    - cd .. && pip install -r requirements.txt
    - test/test_basic_submission.py
