image: ubuntu
# TODO: build image

stages:
  - test

before_script:
  - date && date -u
  - apt-get update && apt-get install -y python3.8 python3.8-dev python3-pip virtualenv
  - pip install -r requirements.txt

unit_tests:
  stage: test
  script:
    - test/test_basic_submission.py
