image: ubuntu
# TODO: build image

stages:
  - test

before_script:
  - date && date -u
  - apt-get update && apt-get install -y python3.8 python3.8-dev python3-pip python-pip virtualenv 

unit_tests:
  stage: test
  script:
    - virtualenv -p python3.7 venv && . venv/bin/activate && pip install -r requirements.txt
    - test/test_basic_submission.py
