image: ubuntu:18.04

stages:
  - test

before_script:
  - date && date -u
  - apt-get update && apt-get install -y python3.8 python3.8-dev python3-pip python-pip virtualenv git apt-transport-https ca-certificates gnupg curl software-properties-common
  - echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y
  - apt-get -y upgrade

after_script:
  - virtualenv -p python3.8 venv && . venv/bin/activate && pip install requests
  - python scripts/post_to_slack.py

staging:
  stage: test
  script:
    - source environment
    - virtualenv -p python3.8 venv && . venv/bin/activate
    - ./venv/bin/python -m pip install --no-cache-dir -r requirements.txt
    - make lint
    - BDCAT_STAGE=staging TERRA_DEPLOYMENT_ENV=alpha test/test_basic_submission.py
  only:
    - master
    - staging
  except:
    - schedules

version_check:
  stage: test
  script:
    - source environment
    - virtualenv -p python3.8 venv && . venv/bin/activate
    - ./venv/bin/python -m pip install --no-cache-dir -r requirements.txt
    - make lint
    - BDCAT_STAGE=staging TERRA_DEPLOYMENT_ENV=alpha test/test_version_check.py
  only:
    - master
    - staging
  except:
    - schedules

prod:
  stage: test
  script:
    - source environment
    - virtualenv -p python3.8 venv && . venv/bin/activate
    - ./venv/bin/python -m pip install --no-cache-dir -r requirements.txt
    - make lint
    - BDCAT_STAGE=prod test/test_basic_submission.py
  only:
    - prod
  except:
    - schedules

dev-prod:
  stage: test
  script:
    - source environment
    - virtualenv -p python3.8 venv && . venv/bin/activate
    - ./venv/bin/python -m pip install --no-cache-dir -r requirements.txt
    - make lint
    - BDCAT_STAGE=prod test/test_basic_submission.py
  except:
    - schedules
    - staging
    - master

dev-staging:
  stage: test
  script:
    - source environment
    - virtualenv -p python3.8 venv && . venv/bin/activate
    - ./venv/bin/python -m pip install --no-cache-dir -r requirements.txt
    - make lint
    - BDCAT_STAGE=staging TERRA_DEPLOYMENT_ENV=alpha test/test_basic_submission.py
  except:
    - schedules
    - prod

scheduled_tests:
  only:
    - schedules
  script:
    - source environment
    - virtualenv -p python3.8 venv && . venv/bin/activate
    - ./venv/bin/python -m pip install --no-cache-dir -r requirements.txt
    - make lint
    - BDCAT_STAGE=staging TERRA_DEPLOYMENT_ENV=alpha test/test_basic_submission.py
